name: Build and Deploy Kotlin WASM Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Kotlin WASM project
      run: ./gradlew wasmJsBrowserDistribution

    - name: Commit and Push to GitHub Pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add artifacts/
        git commit -m "Deploy GitHub Pages" || echo "No changes to commit"
        # Use the PAT for authentication
        git push https://${{ secrets.GH_BOT }}@github.com/${{ github.repository }} main

